services:
  postgres:
    container_name: postgres
    image: "postgres:latest"
    environment:
      - "POSTGRES_DB=${POSTGRES_DB}"
      - "POSTGRES_PASSWORD=${POSTGRES_PASSWORD}"
      - "POSTGRES_USER=${POSTGRES_USER}"
    ports:
      - "${POSTGRES_PORT}:5432"

  backend:
    container_name: backend
    image: al77ex1/reminder
    build: .
    depends_on:
      - postgres
    ports:
      - "${BACKEND_API_PORT}:8080"
      - "${BACKEND_PORT}:5000"
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_USERNAME=${SPRING_DATASOURCE_USERNAME}
      - SPRING_DATASOURCE_PASSWORD=${SPRING_DATASOURCE_PASSWORD}